# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ4R5bI4CfuO-jTeIdSyCMDfYM6nE2A6
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
# 🔄 IMPORTANTE: Importamos KFold para poder realizar la Validación Cruzada (80/20)
from sklearn.model_selection import KFold

def sistema_recomendacion_por_genero():
    # =========================================================================
    # 1. CARGAR EL ARCHIVO DE DATOS
    # =========================================================================
    nombre_archivo = 'titulosunicos.csv'
    try:
        df = pd.read_csv(nombre_archivo, encoding='utf-8')
    except FileNotFoundError:
        print(f"❌ Error: El archivo '{nombre_archivo}' no se encuentra en el entorno.")
        return

    # =========================================================================
    # 2. INTERFAZ DE USUARIO (MENÚ DE GÉNEROS)
    # =========================================================================
    print("🤖 === BIENVENIDO A TU RECOMENDADOR KNN ===")
    print("¿Qué tienes ganas de ver hoy? Selecciona un género:")
    print("1️⃣ - Acción")
    print("2️⃣ - Comedia")
    print("3️⃣ - Drama")
    print("4️⃣ - Ciencia Ficción (Sci-Fi)")
    print("5️⃣ - Terror")
    print("6️⃣ - Romance")
    print("===========================================")

    # Mapeo de la selección del usuario al nombre de la columna en el archivo CSV
    generos = {
        "1": "accion",
        "2": "comedia",
        "3": "drama",
        "4": "scifi",
        "5": "terror",
        "6": "romance"
    }

    opcion = input("Escribe el número de tu género favorito (1-6) y presiona Enter: ")

    if opcion not in generos:
        print("❌ Opción no válida. Por favor, selecciona un número del 1 al 6.")
        return

    genero_elegido = generos[opcion]

    # =========================================================================
    # 3. FILTRAR EL CATÁLOGO POR EL GÉNERO SELECCIONADO
    # =========================================================================
    # Solo nos quedamos con las filas donde el género elegido sea igual a 1
    df_filtrado = df[df[genero_elegido] == 1].reset_index(drop=True)

    if df_filtrado.empty:
        print(f"No encontramos contenidos para el género {genero_elegido}.")
        return

    print(f"\n🔎 Analizando las mejores opciones de '{genero_elegido.upper()}' dentro del catálogo...")

    # =========================================================================
    # 4. PREPARAR LAS CARACTERÍSTICAS (FEATURES)
    # =========================================================================
    # Estas son las columnas numéricas que el algoritmo usará para comparar las películas
    features = df_filtrado[['accion', 'comedia', 'drama', 'scifi', 'terror', 'romance', 'rating', 'es_serie']]

    # =========================================================================
    # 🔄 5. BLOQUE DE CROSS-VALIDATION (VALIDACIÓN CRUZADA - 5 FOLDS)
    # =========================================================================
    print("\n🔄 Iniciando Validación Cruzada (5-Fold Cross-Validation)...")
    print("-" * 60)

    # Configuración del K-Fold:
    # n_splits=5 significa que dividirá los datos en 5 partes.
    # Esto genera automáticamente la proporción 80% (4 partes) y 20% (1 parte).
    # shuffle=True mezcla las películas de forma aleatoria antes de dividir.
    # random_state=42 asegura que el resultado de la mezcla siempre sea el mismo.
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    scores_distancia = [] # Lista vacía para guardar los resultados de cada iteración

    # Iniciamos el bucle que se ejecutará 5 veces (una por cada pliegue/fold)
    for fold, (train_index, test_index) in enumerate(kf.split(features), 1):

        # Separación real de los datos usando los índices calculados por KFold:
        # X_train obtiene el 80% de los datos para entrenar el modelo en esta vuelta.
        # X_test obtiene el 20% restante para evaluar el modelo en esta vuelta.
        X_train = features.iloc[train_index]
        X_test = features.iloc[test_index]

        # Control de seguridad: Si por alguna razón un set queda vacío, saltamos la iteración
        if len(X_train) == 0 or len(X_test) == 0:
            continue

        # Creamos un modelo KNN temporal exclusivo para este Fold
        modelo_fold = NearestNeighbors(metric='cosine', algorithm='brute')

        # Entrenamos al modelo temporal usando ÚNICAMENTE el 80% de datos (X_train)
        modelo_fold.fit(X_train)

        # Evaluamos el modelo pasándole el 20% de datos ocultos (X_test)
        # Le pedimos que encuentre las distancias a sus vecinos más cercanos
        distancias_test, _ = modelo_fold.kneighbors(X_test, n_neighbors=min(5, len(X_train)))

        # Calculamos la distancia matemática promedio de este intento
        # (En distancia coseno, un valor más cercano a 0 significa mayor similitud)
        distancia_promedio = np.mean(distancias_test)

        # Guardamos el resultado del Fold en nuestra lista
        scores_distancia.append(distancia_promedio)

        print(f"   🔹 Fold {fold} (80% Train / 20% Test) -> Distancia promedio en test = {distancia_promedio:.4f}")

    # Una vez terminadas las 5 vueltas, calculamos las métricas estadísticas globales
    cv_mean = np.mean(scores_distancia) # El promedio de los 5 intentos
    cv_std = np.std(scores_distancia)   # La desviación estándar (mide la estabilidad del modelo)

    print("-" * 60)
    print(f"📊 RENDIMIENTO GLOBAL DEL RECOMENDADOR:")
    print(f"   -> Distancia coseno media (Error): {cv_mean:.4f}")
    print(f"   -> Estabilidad del modelo (Desviación Estándar): ±{cv_std:.4f}")
    print("=========================================================================\n")

    # =========================================================================
    # 6. ENTRENAR EL MODELO FINAL (CON EL 100% DE LOS DATOS)
    # =========================================================================
    # Una vez validado que el modelo es estable, entrenamos el KNN definitivo con todo el catálogo
    modelo_knn = NearestNeighbors(metric='cosine', algorithm='brute')
    modelo_knn.fit(features)

    # Creamos un "perfil ideal" basado en lo que busca el usuario
    perfil_ideal = np.zeros(features.shape[1])
    columnas_lista = list(features.columns)

    # Activamos el género elegido y apuntamos a una calificación perfecta (10.0)
    perfil_ideal[columnas_lista.index(genero_elegido)] = 1
    perfil_ideal[columnas_lista.index('rating')] = 10.0

    # =========================================================================
    # 7. GENERAR Y MOSTRAR LAS RECOMENDACIONES
    # =========================================================================
    # El modelo busca los 5 contenidos reales más parecidos a nuestro "perfil ideal"
    distancias, indices = modelo_knn.kneighbors(perfil_ideal.reshape(1, -1), n_neighbors=5)

    print(f"🍿 Aquí tienes las 5 mejores recomendaciones de {genero_elegido.capitalize()}:")
    print("=" * 80)

    # Iteramos para imprimir los resultados en la consola de manera amigable
    for i in range(len(distancias.flatten())):
        idx = indices.flatten()[i]
        distancia = distancias.flatten()[i]
        recomendacion = df_filtrado.iloc[idx]

        # Identificamos si es serie o película
        tipo_rec = "Serie 📺" if recomendacion['es_serie'] == 1 else "Película 🍿"

        # Convertimos la distancia coseno a un porcentaje de similitud (coincidencia)
        porcentaje_similitud = (1 - distancia) * 100

        print(f"📌 {recomendacion['titulo']}")
        print(f"   Formato: {tipo_rec} | Calificación: {recomendacion['rating']}/10 | Coincidencia de perfil: {porcentaje_similitud:.2f}%")
        print("-" * 80)

if __name__ == "__main__":
    sistema_recomendacion_por_genero()