# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ4R5bI4CfuO-jTeIdSyCMDfYM6nE2A6
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors

def sistema_recomendacion_por_genero():
    # 1. Cargar el archivo con títulos únicos
    nombre_archivo = 'titulosunicos.csv'
    try:
        df = pd.read_csv(nombre_archivo, encoding='utf-8')
    except FileNotFoundError:
        print(f"❌ Error: El archivo '{nombre_archivo}' no se encuentra en el entorno.")
        return

    # 2. Mostrar menú de géneros en la consola
    print("🤖 === BIENVENIDO A TU RECOMENDADOR KNN ===")
    print("¿Qué tienes ganas de ver hoy? Selecciona un género:")
    print("1️⃣ - Acción")
    print("2️⃣ - Comedia")
    print("3️⃣ - Drama")
    print("4️⃣ - Ciencia Ficción (Sci-Fi)")
    print("5️⃣ - Terror")
    print("6️⃣ - Romance")
    print("===========================================")

    # Mapeo de la selección al nombre de la columna en el CSV
    generos = {
        "1": "accion",
        "2": "comedia",
        "3": "drama",
        "4": "scifi",
        "5": "terror",
        "6": "romance"
    }

    opcion = input("Escribe el número de tu género favorito (1-6) y presiona Enter: ")

    if opcion not in generos:
        print("❌ Opción no válida. Por favor, selecciona un número del 1 al 6.")
        return

    genero_elegido = generos[opcion]

    # 3. Filtrar el catálogo: solo nos quedamos con los contenidos que SÍ tienen ese género (valor == 1)
    df_filtrado = df[df[genero_elegido] == 1].reset_index(drop=True)

    if df_filtrado.empty:
        print(f"No encontramos contenidos para el género {genero_elegido}.")
        return

    print(f"\n🔎 Analizando las mejores opciones de '{genero_elegido.upper()}' dentro del catálogo...")

    # 4. Preparar características para el KNN
    # El algoritmo comparará qué tan fuertes son en los otros géneros y buscará los mejores ratings
    features = df_filtrado[['accion', 'comedia', 'drama', 'scifi', 'terror', 'romance', 'rating', 'es_serie']]

    # Configurar KNN
    modelo_knn = NearestNeighbors(metric='cosine', algorithm='brute')
    modelo_knn.fit(features)

    # Creamos un "perfil ideal": Buscamos contenidos que pertenezcan al género elegido y tengan un rating perfecto (10.0)
    perfil_ideal = np.zeros(features.shape[1])
    # Activamos el género elegido en nuestro perfil ideal
    columnas_lista = list(features.columns)
    perfil_ideal[columnas_lista.index(genero_elegido)] = 1
    perfil_ideal[columnas_lista.index('rating')] = 10.0  # Apuntamos a lo mejor calificado

    # 5. Encontrar los 5 contenidos más cercanos a nuestro perfil ideal
    distancias, indices = modelo_knn.kneighbors(perfil_ideal.reshape(1, -1), n_neighbors=5)

    print(f"\n🍿 Aquí tienes las 5 mejores recomendaciones de {genero_elegido.capitalize()}:")
    print("=" * 80)

    for i in range(len(distancias.flatten())):
        idx = indices.flatten()[i]
        distancia = distancias.flatten()[i]
        recomendacion = df_filtrado.iloc[idx]

        tipo_rec = "Serie 📺" if recomendacion['es_serie'] == 1 else "Película 🍿"
        porcentaje_similitud = (1 - distancia) * 100

        print(f"📌 {recomendacion['titulo']}")
        print(f"   Formato: {tipo_rec} | Calificación: {recomendacion['rating']}/10 | Coincidencia de perfil: {porcentaje_similitud:.2f}%")
        print("-" * 80)

if __name__ == "__main__":
    sistema_recomendacion_por_genero()